website:
  title: "Vade Mecum"
  search: true
  sidebar:
    style: "docked"
    logo: "img/logo/logo.png"
    contents:
      - href: index.qmd
        text: "Home"
      - auto: "doc/"
      - href: https://github.com/BridgeQG/VadeMecum
        text: "GitHub Project"
      - href: about.qmd
      - section: "Menu"
        contents:
          - href: "doc/Low-energy_table-top_experiments.qmd"
          - href: "doc/blablabla2.qmd"

bibliography: bib/references.bib
csl: bib/american-mathematical-society-label.csl

project:
  type: website

filters:
  - lua/latex-to-quarto.lua

format:
  html:
    theme: cosmo
    math: mathjax
    css: include/css-config.css
