---
title: 'Equivalence Principle, locality and quantum gravity'
nocite: |
  @Misner:1973prb, @Okon:2010kn, @DiCasola:2013iia, @Paunkovic:2022nkc
---

\subsubsection{Introduction and purpose}

The purpose of the equivalence principle (EP) is to \textit{prescribe the interaction between gravity and matter}, i.e., between gravitational and non-gravitational degrees of freedom in nature. EP is one of the most fundamental principles in modern physics, a cornerstone of Einstein's theory of [general relativity](https://en.wikipedia.org/wiki/General_relativity) and of the [Standard Model](https://en.wikipedia.org/wiki/Standard_Model) of elementary particle physics.

\subsubsection{The statement of EP}

In its most general and abstract form, the equivalence principle states:

\textit{The equations of motion for matter coupled to gravity are locally identical to the equations of motion for matter in the absence of gravity}.

Here, the notion of [\textit{locality}](/doc/2ndlevel/locality.qmd) refers to an infinitesimally small region around a single point in spacetime, in which the dynamics of matter is being discussed.

\subsubsection{Various flavors of EP}

Depending on the details on how one chooses to describe gravity, matter, and equations of motion, the above abstract statement of EP can be rephrased in various (inequivalent) ways. The most common [flavors](/doc/2ndlevel/flavors_EP.qmd) are as follows:

- [Newtonian EP](/doc/2ndlevel/flavors_EP.qmd) --- equality of gravitational and inertial mass. Matter is described by point particles, equations of motion are Newton's laws, while gravity is described by Newton's law of universal gravity. EP is rephrased as a constraint between the parameter featuring in Newton's second law of motion and the parameter featuring in Newton's law of universal gravity.
- [Galilean EP](/doc/2ndlevel/flavors_EP.qmd) --- universality of free fall. Matter is described by point particles, equations of motion are implicit and qualitative, as is the description of gravity. EP is rephrased as a comparison of the motion between different types of particles, given the same gravitational background.
- [Einstein's EP](/doc/2ndlevel/flavors_EP.qmd) --- local equivalence between inertia and gravity. Matter is described mostly by point particles, equations of motion are implicit, and gravity is described as a field, uniform across a ``local laboratory''. EP is rephrased as the local indistinguishability between inertial and gravitational forces.
- [Weak EP](/doc/2ndlevel/flavors_EP.qmd) --- geodesic trajectories of free particles. Matter is described by point particles, equations of motion are geodesic equations in a given curved background geometry, and gravity is described as the curvature of spacetime. EP is rephrased as a statement that locally one cannot distinguish between a geodesic in curved spacetime and a straight line in flat spacetime.
- [Strong EP](/doc/2ndlevel/flavors_EP.qmd) --- minimal coupling between matter fields and gravity. Both matter and gravity are described as fields over the spacetime manifold. The equations of motion are implicit, but assumed to be local. EP is rephrased as a restriction that matter does not couple directly to spacetime curvature, but only to the metric and connection, in the equations of motion for matter fields.

\subsubsection{Generalizations of EP}

In addition to gravity, a variant of the strong EP can be formulated for [strong, weak and electromagnetic](https://en.wikipedia.org/wiki/Fundamental_interaction) interaction, and is implemented in the [\textit{Standard Model}](https://en.wikipedia.org/wiki/Standard_Model) of elementary particle physics. In the context of [\textit{quantum gravity}](/doc/quantum_gravity.qmd) research, formulating the [quantum EP](/doc/2ndlevel/quantum_EP.qmd) represents an active research topic.

## List of Authors {id="authors" .appendix}

- Nikola Paunkovic
- Marko Vojinovic
