---
title: 'In-vacuo dispersion'
---

In-vacuo dispersion is an effect related to the hypothesis of a quantum gravity scale [modified dispersion relation (MDR)](/doc/2ndlevel/InVacuoDispersion/MDR.qmd), which is described by the Hamiltonian of a relativistic particle characterizing its propagation in a [quantum spacetime](/doc/2ndlevel/quantum_spacetime.qmd). Deviations from the general relativistic dispersion relations are often (but not always) associated with either the [violation or deformation of relativistic symmetries](/doc/LIV_DSR.qmd). The core idea is to describe the effects of quantum gravity as a deformation of the classical trajectory of particles---a deformation that grows with the particle's energy and is suppressed by the quantum gravity energy scale \cite{Amelino-Camelia:1997ieq,Addazi:2021xuf}.

Since, in the context of quantum gravity, the relevant energies are ultra-relativistic, one can often focus on the massless case. For certain types of [MDRs](/doc/2ndlevel/InVacuoDispersion/MDR.qmd), the speed of a massless particle becomes energy-dependent in vacuum, which is the origin of the effect's name.

For this reason, if particles are emitted from a given source with an energy difference, they arrive at a detector with a time difference proportional to the product of the energy difference and the propagation distance, but suppressed by the \textbf{quantum gravity energy scale}. This is a quantum spacetime-induced \textbf{time delay} effect, analogously to what the propagation of light through a medium ($\eta$ -- phenomenological parameter, $M_P$ --Planck mass, $D(z)$ -- redshift-dependent distance factor)
\begin{equation*}
\Delta t = \eta D(z) \frac{\Delta E}{M_P}
\end{equation*}
If these particles propagate over cosmological distances, even a modification suppressed by the Planck scale could produce a measurable effect with modern telescopes.


\textbf{Different formulations of the time delay} effect have been proposed based on various hypotheses, such as the coupling between the energy-momentum of the particle and the spacetime metric, the \textbf{local symmetries of spacetime}, and the redshift dependence of the quantum gravity scale \cite{Addazi:2021xuf}.
