---
title: 'Violation and Deformation of Relativistic Symmetries'
---

[Relativistic symmetries](https://en.wikipedia.org/wiki/Special_relativity) play a central role in modern physics, but many approaches to quantum gravity suggest that these symmetries may not remain exactly the classical (local) Lorentz or Poincaré transformations of special relativity at the highest energy scales. This motivates the investigation of scenarios in which Lorentz and Poincaré symmetries are either violated or deformed.
In the case of \textbf{Lorentz Invariance Violation (LIV)}, Lorentz symmetry is broken explicitly (as in many [effective field theory descriptions](/doc/2ndlevel/Standard_model_extensions.qmd)) or spontaneously (when fields acquire vacuum expectation values that select preferred directions in spacetime), so that physics is formulated in a preferred frame. In contrast, \textbf{deformed-symmetry frameworks (DSR -- Doubly (or Deformed) Special Relativity} \cite{Amelino-Camelia:2000stu}, preserve the [relativity principle](https://en.wikipedia.org/wiki/Special_relativity) but modify the transformation laws between observers by introducing an additional invariant scale (usually associated with the [Planck length](https://simple.wikipedia.org/wiki/Planck_length), $\ell_P \approx 1.61 \times 10^{-35}\,\mathrm{m} \approx 1.30 \times 10^{-29}\,\mathrm{eV}^{-1}$).
Although both approaches explore possible imprints of a [quantum or discrete structure of spacetime](/doc/2ndlevel/Emergent_nonclassical_and_fuzzy_spacetime.qmd), they lead to
conceptually different kinematics and, as discussed below, to very different phenomenological expectations.


[Modified Dispersion Relations (MDR)](/doc/2ndlevel/Modified_dispersion_relations.qmd) represent one of the most studied ways to depart from special-relativistic kinematics and have been extensively studied in both LIV and DSR scenarios, particularly for their phenomenological implications, even though not all LIV and DSR models necessarily feature a MDR. The most-studied LIV models typically arise from symmetry-breaking operators in [effective field theory](/doc/2ndlevel/Standard_model_extensions.qmd). On the other hand, DSR models often arise from constructions in which deformed spacetime symmetries are formulated within a [Hopf-algebra (quantum groups) framework](/doc/2ndlevel/Hopf_algebra.qmd) encoding high-energy modifications of the [Poincaré symmetry](https://en.wikipedia.org/wiki/Poincar%C3%A9_group).
In LIV and DSR scenarios, nontrivial/nonlinear energy-momentum conservation rules, formalized as a modified composition law for four-momenta, have also been considered. However, while in LIV a modified composition law is not strictly required, in DSR it is generally considered necessary to ensure the compatibility between the relativity principle and the presence of an additional invariant scale.
In DSR, the modified composition law admits a geometric interpretation as a rule for non-linear  \textit{translations in momentum space}, and it can also be understood algebraically as part of the coalgebra structure of  [Hopf algebras](/doc/2ndlevel/Hopf_algebra.qmd).
These structures commonly appear in models with  [curved momentum space](/doc/2ndlevel/curved_momentum_space.qmd),  [noncommutative spacetimes](/doc/2ndlevel/noncommutative_spacetime.qmd), or  [quantum-group symmetries](/doc/2ndlevel/Hopf_algebra.qmd), and can lead to  [relative locality](/doc/2ndlevel/relative_locality.qmd), namely an observer dependence of event localisation that may also arise in more general contexts.
A more fundamental framework for LIV and DSR models is based on (quantum) fields in  [noncommutative spacetimes](/doc/2ndlevel/noncommutative_spacetime.qmd), which in turn allow for the study of [discrete symmetry operators](/doc/2ndlevel/discrete_symmetries.qmd)  C (charge conjugation),  P (parity),  T (time reversal), and  \textbf{scattering amplitudes}.
In this context,  loop corrections to tree-level diagrams often exhibit  [UV/IR mixing](/doc/IR-UV_mixing.qmd), where Lorentz-breaking (or deformation) scales, and cutoff scales interact in a non-trivial way, with potentially observable consequences.
Some of these models, which may or may not imply MDRs, may also lead to a Planck-scale [Generalized Heisenberg Uncertainty Principle (GUP)](/doc/2ndlevel/GUP.qmd).


The phenomenology associated with the LIV and DSR frameworks is markedly different.
The most studied effect in both LIV and DSR scenarios is [in-vacuo dispersion](/doc/invacuo_dispersion.qmd), arising from MDRs.
However, other effects that are generally present in LIV frameworks, like [threshold anomalies](/doc/2ndlevel/Threshold_anomalies.qmd),  [vacuum birefringence](/doc/2ndlevel/Vacuum_birefringence.qmd), or  [modified decay channels](/doc/2ndlevel/Modified_decay_channels), are typically highly suppressed in DSR scenarios, or not present at all if they violate the relativity principle.
For example, they neither open nor close thresholds of reactions that, in LIV scenarios, may become allowed or forbidden.
[Astroparticle messengers](/doc/Astrophyisical_probes) (high-energy gamma rays, neutrinos, and cosmic rays), together with gravitational-wave, gravitational-lensing and \textbf{black-hole} observations, offer access to regimes where small departures from relativistic symmetries may accumulate or become detectable within a multimessenger approach.
A generalization to [expanding spacetimes] of [LIV models](/doc/2ndlevel/LIV_FLRW.qmd) and of DSR models(/doc/2ndlevel/DSR_FLRW.qmd) in the presence of a \textbf{de Sitter}-invariant scale) has been developed in recent years.

Such effects can also manifest in the low-energy regime. In quantum mechanical systems, LIV and DSR may induce modifications in time evolution. For instance, a \textbf{modified Schrödinger equation} arises from [modified dispersion relations](/doc/2ndlevel/Modified_dispersion_relations.qmd), and \textbf{decoherence} occurs when the \textbf{quantum gravity scale} is treated as a stochastic quantity or when modified symmetries are present.
Also, C, P, and T transformations can interact non-trivially with the LIV or DSR scales, leading to additional phenomenological signatures. Precision laboratory and collider or accelerator experiments, often aimed at measuring differences in properties between particles and antiparticles (e.g.\ \textbf{decay times}), provide complementary tests of these effects.
Taken together, astroparticle, astrophysical, and low-energy laboratory probes form a broad landscape in which the implications of the deformation or violation of relativistic symmetries can be systematically explored.

General reviews of these topics can be found in \cite{Mattingly:2005re}, \cite{Amelino-Camelia:2008aez}, \cite{Addazi:2021xuf}


