---
title: 'Quantum Reference Frames'
nocite: |
  @Bartlett_2007, @Giacomini_2017_covariance, @Vanrietvelde_2018a, @delaHamette_2020, @Loveridge:2017pcv
---
\textit{in Relativistic Quantum Information and Quantum Gravity}

\subsubsection{Motivation and Context.}
With the development of relativity theories came a replacement of absolute space and time with the more relational notion of spacetime, which obtains its operational meaning through measurements of relative distances and durations defined by physical systems serving as references. By the same token, in a world described by quantum theory, reference frames should be subject to those laws that govern the objects to be described. Just as extent, duration, and motion in relativity must be understood relative to a given frame, the central objects of the quantum description of nature -- states, observables, and probabilities -- should be understood as relative to a given quantum reference frame (QRF). This has implications in the foundations of quantum mechanics, provoking a re-examination of the meaning of superposition, entanglement, and indeterminacy, in quantum information processing tasks in which agents lack access to a reference frame, and in quantum field theory and quantum gravity wherein relational descriptions provided by quantum reference frames may allow for background-independence to be manifested.

\subsubsection{Core Concepts and Approaches.}
In general, a QRF is a physical system associated with a [symmetry group  $G$](https://en.wikipedia.org/wiki/Symmetry_(physics)), under which it transforms covariantly. The properties of other systems can then be described relative to the chosen QRF with so-called [relational observables](/doc/2ndlevel/Relational_observables.qmd).
The descriptions relative to different QRFs are related by [QRF transformations](/doc/2ndlevel/QRF_transformations.qmd).

While the main approaches, namely the [perspectival](/doc/2ndlevel/QRF_approaches.qmd), [perspective-neutral](/doc/2ndlevel/QRF_approaches.qmd), [extra-particle](/doc/2ndlevel/QRF_approaches.qmd), and [operational approaches](/doc/2ndlevel/QRF_approaches.qmd) agree on these basic ingredients, they differ both mathematically and in their physical assumptions. In particular, they may disagree on which quantities are measurable from within a QRF, and on whether one includes only [internal](/doc/2ndlevel/QRF_approaches.qmd) or also [external frames](/doc/2ndlevel/QRF_approaches.qmd).
Different frameworks can deal with [ideal](/doc/2ndlevel/QRF_approaches.qmd) (also referred to as perfect), [non-ideal](/doc/2ndlevel/QRF_approaches.qmd) (or imperfect), sharp or unsharp QRFs, which differ in the extent to which they break the symmetry $G$.
Operationally, this determines whether frame changes can be implemented exactly or only approximately.

When describing systems relative to different QRFs, properties such as superposition, entanglement, or coherence, become frame-dependent due to the [relativity of subsystems](/doc/2ndlevel/Subsystems_relativity.qmd) and the way we identify configurations across the different branches of a superposition. This also raises new questions, such as the [paradox of the third particle](/doc/2ndlevel/Subsystems_relativity.qmd).

\subsubsection{Connections to Quantum Gravity and Gauge Theory.}

Quantum reference frames arise naturally in the presence of gauge symmetries, where physical observables must be defined relationally with respect to dynamical degrees of freedom rather than external coordinates. This places QRFs at the core of [constraint quantization](/doc/2ndlevel/Constraint_quantization.qmd) (imposing gauge constraints at the quantum level),
[Dirac observables](/doc/2ndlevel/Constraint_quantization.qmd) (gauge-invariant physical quantities), and the problem of [time and localization in quantum gravity](/doc/2ndlevel/The_problem_of_locality.qmd), where spacetime itself is quantum. In this setting, changing a quantum reference frame can be understood as a quantum generalization of gauge transformations, relating different relational descriptions of the same physical situation.

In approaches to [emergent spacetime](/doc/Emergent_nonclassical_and_fuzzy_spacetime.qmd) and [discrete quantum gravity](/doc/2ndlevel/Discrete_QG.qmd), quantum reference frames provide a natural language for describing geometry without background structures and for comparing quantum geometries across superposed configurations.
QRFs have further been linked to [type reduction in algebraic quantum field theory](/doc/Algebraic_QFT.qmd) and the emergence of effective classical descriptions from fundamentally relational quantum theories. This suggests a unifying role for quantum reference frames in connecting quantum information–theoretic structures with gravitational dynamics.


At the quantum level, these boundary symmetries can be interpreted as quantum reference frames associated with the boundary, enabling the construction of relational bulk observables as gravitationally [dressed observables](/doc/2ndlevel/Constraint_quantization.qmd). This perspective has become central to finite-distance [holography] and to reformulating quantum gravity in quantum information-theoretic terms.

Finally, quantization of gravity, where geometry itself becomes a quantum variable, naturally leads to the notion of a [quantum spacetime](/doc/2ndlevel/Quantum_spacetime).


The symmetries of such spacetimes are described by [quantum groups and Hopf algebras](/doc/2ndlevel/Hopf_algebra.qmd), whose transformation properties imply a corresponding \textit{quantization of observers and reference frames}. Moreover, the quantum reference frame transformations introduced in are also endowed with a quantum group symmetry. This further supports the view that quantum reference frames are not auxiliary tools, but fundamental ingredients of a fully relational formulation of quantum gravity.


\subsubsection{Multiple Perspectives, Shared Goals.}

 The variety of contemporary frameworks for describing and using quantum reference frames reflects the different contexts in which the concept first appeared. In particular, approaches motivated by constraint quantization and gauge symmetry often lead to mathematical structures that differ from `quantum-native' approaches, where symmetries are imposed directly at the level of observable algebras. The precise relation between the different approaches is still an active area of research. Nevertheless, there is substantial overlap in motivation, structures, and insights.
The ultimate goals of constructing diffeomorphism-invariant quantum field theories and of applying QRFs to quantum gravity are shared across all approaches, and it is likely that insights from each framework will be needed.

## List of Authors {id="authors" .appendix}
- Angel Ballesteros
- Goffredo Chirco
- Anne-Catherine de la Hamette
- Renata Ferrero
- Sébastien C. Garmier
- Viktoria Kabel
- Etera Livine
- Fedele Lizzi
- Leon Loveridge
- Antonino Marciano
- Daniele Oriti
- and Roman Pasechnik
